### PR TITLE
Added functorial interface

### PR DESCRIPTION
**Pull request by igarnier**
A basic, thin functorial interface on top of the generic code

### CODE REVIEW

**Comment by UnixJunkie** [comment]
Thanks for this contribution Ilias, I will review it tomorrow.
Happy to see you doing open source in Ocaml.
Could you accelerate something cool thanks to a vp-tree?

**Comment by igarnier** [comment]
I'm implementing an agglomerative clustering algorithm, as described here for example: https://nlp.stanford.edu/IR-book/html/htmledition/hierarchical-agglomerative-clustering-1.html
The first phase of the algorithm is to compute the closest neighbour for all elements, along with the distance to that neighbour. I think using a vp-tree for that is a perfect match, no?

**Comment by UnixJunkie** [comment]
Yes, it should be perfect. Note however that this vp-tree implementation is not for a very large number of points.
For a good reference about clustering algorithms and stats, this free one is great: https://web.stanford.edu/~hastie/Papers/ESLII.pdf

**Comment by UnixJunkie** [comment]
related to https://github.com/UnixJunkie/vp-tree/issues/1

**Pull request merged**
